# # a=5
# # print(a)
# a,b=input().split(",")
# print(a,b)
# print(type(a))
# print(type(b))
# a=int(a)
# print(type(a))
# a,b=input("请输入姓名和年龄,用逗号隔开").split(",")
# #print("姓名是："+a+","+"年龄是:"+b)
# print("%s 的年龄是 %d 岁"%(a,int(b)))
c,d=input("请输入c和d的值").split(",")
print("%s的年龄是%s岁"%(c,d))
